import mongoose from "mongoose";

// Defining Schema
const ac2tSchema = new mongoose.Schema({
  BOGIE_TYPE_NO:                                            { type: String,  trim: true },
  SHIFT:                                            { type: String,  trim: true },
  APPLICABLE_WI_NO:                                          { type: String,  trim: true },
  FRAME_NO_MAKE:                           { type: String,  trim: true },
  WHEEL_AXLE_NO:                                          { type: String,  trim: true },
  BRAKE_CYLINDER_NO_MAKE:                                                                       { type: String,  trim: true },
  VSA_PRIMARY_SUSP_NO_MAKE:                                             { type: String,  trim: true },
  VSA_SECONDARY_SUSP_NO_MAKE:                                     { type: String,  trim: true },
  LATERAL_SHOCK_ABSORBER_NO_MAKE:                                       { type: String,  trim: true },
  BOLSTER_NO_MAKE:                                                { type: String,  trim: true },
  Z11_TARE:                                                  { type: String,  trim: true },
  Z11_TARE_REMARK:                                                 { type: String, trim: true },
  Z11_GROSS:                                                 { type: String,  trim: true },
  Z11_GROSS_REMARK:                                     { type: String, trim: true },
  Z31_TARE:                                                  { type: String,  trim: true },
  Z31_TARE_REMARK:                                       { type: String, trim: true },
  Z31_GROSS:                                        { type: String,  trim: true },
  Z31_GROSS_REMARK:                                         { type: String, trim: true },
  Z41_TARE:                                    { type: String,  trim: true },
  Z41_TARE_REMARK:                                            { type: String, trim: true },
  Z41_GROSS:                                { type: String,  trim: true },
  Z41_GROSS_REMARK:                                                  { type: String, trim: true },
  Z21_TARE:                                             { type: String,  trim: true },
  Z21_TARE_REMARK:                                     { type: String, trim: true },
  Z21_GROSS:                                         { type: String,  trim: true },
  Z21_GROSS_REMARK:                                          { type: String, trim: true },
  X_TARE:                                                { type: String,  trim: true },
  X_TARE_REMARK:                                                         { type: String, trim: true },
  X_GROSS:                                     { type: String,  trim: true },
  X_GROSS_REMARK:                                         { type: String, trim: true },
  Z12_PLUS_Z22_BY2_TARE:                                               { type: String,  trim: true },
  Z12_PLUS_Z22_BY2_TARE_REMARK:                                               { type: String, trim: true },
  Z12_PLUS_Z22_BY2_GROSS:                                                             { type: String,  trim: true },
  Z12_PLUS_Z22_BY2_GROSS_REMARK:                                                                  { type: String, trim: true },
  Z32_PLUS_Z42_BY2_TARE:                                          { type: String,  trim: true },
  Z32_PLUS_Z42_BY2_TARE_REMARK:                                   { type: String, trim: true },
  Z32_PLUS_Z42_BY2_GROSS:                                                 { type: String,  trim: true },
  Z32_PLUS_Z42_BY2_GROSS_REMARK:                                          { type: String, trim: true },
  X14_TARE:                                                                       { type: String,  trim: true },
  X14_TARE_REMARK:                                                    { type: String, trim: true },
  X14_GROSS:                                                 { type: String,  trim: true },
  X14_GROSS_REMARK:                                                    { type: String, trim: true },
  X24_TARE:                                                        { type: String,  trim: true },
  X24_TARE_REMARK:                                                           { type: String, trim: true },
  X24_GROSS:                                                                    { type: String,  trim: true },
  X24_GROSS_REMARK:                                                                     { type: String, trim: true },
  Y13_TARE:                                                                  { type: String,  trim: true },
  Y13_TARE_REMARK:                                                               { type: String, trim: true },
  Y13_GROSS:                                                                 { type: String,  trim: true },
  Y13_GROSS_REMARK:                                                            { type: String, trim: true },
  Y33_TARE:                                                    { type: String,  trim: true },
  Y33_TARE_REMARK:                                                    { type: String, trim: true },
  Y33_GROSS:                                           { type: String,  trim: true },
  Y33_GROSS_REMARK:                                     { type: String, trim: true },
  A_SIDE_TARE:                                      { type: String,  trim: true },
  A_SIDE_TARE_REMARK:                                               { type: String, trim: true },
  A_SIDE_GROSS:                               { type: String,  trim: true },
  A_SIDE_GROSS_REMARK:                                { type: String, trim: true },
  B_SIDE_TARE:                                                                  { type: String,  trim: true },
  B_SIDE_TARE_REMARK:                                        { type: String, trim: true },
  B_SIDE_GROSS:                                                                      { type: String,  trim: true },
  B_SIDE_GROSS_REMARK:                                                  { type: String, trim: true },
  TEST_PASSED:                                                        {type:Boolean,required:true},
  Y_TARE:                                                          { type: String,  trim: true },
  Y_GROSS:                                                          { type: String,  trim: true },
  A_TARE:                                                     { type: String,  trim: true },
  B_TARE:                                                    { type: String,  trim: true },
  Z133_PLUS_Z23_BY2_TARE:                                      { type: String,  trim: true },
  Z133_PLUS_Z23_BY2_TARE_REMARK:                                { type: String,  trim: true },
  X_MINUS_1_TARE:                                                 { type: String,  trim: true },
  X_MINUS_1_TARE_REMARK:                                             { type: String,  trim: true },
  Y_MINUS_1_TARE:                                                 { type: String,  trim: true },
  Y_MINUS_1_TARE_REMARK:                                          { type: String,  trim: true },
  X15_TARE:                                                          { type: String,  trim: true },
  X15_TARE_REMARK:                                                   { type: String,  trim: true },
  X25_TARE:                                                          { type: String,  trim: true },
  X25_TARE_REMARK:                                                          { type: String,  trim: true },
  Y14_TARE:                                                            { type: String,  trim: true },
  Y14_TARE_REMARK:                                                      { type: String,  trim: true },
  Y34_TARE:                                                            { type: String,  trim: true },
  Y34_TARE_REMARK:                                                      { type: String,  trim: true },






});

// Model
const AC2TModel = mongoose.model("ac2t", ac2tSchema);

export default AC2TModel;
